# Generated by Django 5.0.2 on 2024-03-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-id']},
        ),
    ]
