# Generated by Django 4.2.11 on 2024-03-14 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calendar_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 14, 14, 54, 26, 585397)),
        ),
    ]
