# Generated by Django 4.2.11 on 2024-03-14 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customuser_calendar_id_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 14, 15, 25, 14, 631646)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
